// <auto-generated />
using ConsysApi.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsysApi.Data.Migrations
{
    [DbContext(typeof(ConsysContext))]
    [Migration("20240628053829_UpdateUsuarios")]
    partial class UpdateUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConsysApi.Data.Model.Produtos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("NOME");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INT")
                        .HasColumnName("QUANTIDADE");

                    b.Property<decimal>("Valor")
                        .HasColumnType("DECIMAL(14,6)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nome" }, "IX_NOME_PRODUTO");

                    b.ToTable("PRODUTOS", (string)null);
                });

            modelBuilder.Entity("ConsysApi.Data.Model.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Crud")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("VARCHAR(7)")
                        .HasColumnName("CRUD");

                    b.Property<string>("NomeId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("VARCHAR(25)")
                        .HasColumnName("NOME_ID");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("SENHA");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NomeId" }, "IX_NOME_ID")
                        .IsUnique();

                    b.HasIndex(new[] { "Id" }, "IX_PK_ID")
                        .IsUnique();

                    b.ToTable("USUARIOS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
