#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# Use a imagem oficial do PostgreSQL
# FROM postgres:13

# Variáveis de ambiente para configurar o PostgreSQL
#ENV POSTGRES_DB consys_database
#ENV POSTGRES_USER consys
#ENV POSTGRES_PASSWORD 12345678

# Copiar arquivos de inicialização do banco de dados
# COPY init.sql /docker-entrypoint-initdb.d/

# Expor a porta padrão do PostgreSQL
# EXPOSE 5432
